/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetodesktop;

/**
 *
 * @author HP
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbResultado = new javax.swing.JLabel();
        btCalculaPeso = new javax.swing.JButton();
        labelAltura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelSexo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frame1"); // NOI18N

        lbResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbResultado.setText("Hello World");

        btCalculaPeso.setText("Calcular");
        btCalculaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculaPesoActionPerformed(evt);
            }
        });

        labelAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelAlturaActionPerformed(evt);
            }
        });

        jLabel1.setText("Altura (ex: 1.55)");

        jLabel2.setText("Peso (Kg)");

        jLabel3.setText("Para Mulher(1) / Homem(2)");

        labelSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCalculaPeso)
                    .addComponent(labelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(labelSexo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelAltura, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btCalculaPeso)
                .addGap(15, 15, 15)
                .addComponent(lbResultado)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalculaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculaPesoActionPerformed
            
        Integer sexo = Integer.parseInt(labelSexo.getText());
        Double peso =  Double.parseDouble(labelPeso.getText());
        Double altura = Double.parseDouble(labelAltura.getText());
        
        Double resultado = peso / (altura * altura);
        
        switch(sexo){
            case 1: 
                if(resultado < 19.1){
            lbResultado.setText("Abaixo do peso");
        }if(resultado > 19.1 && resultado < 25.8){
            lbResultado.setText("Peso normal");
        }if(resultado > 25.8 && resultado <27.3){
            lbResultado.setText("Marginalmente acima do peso");
        }if(resultado > 27.3 && resultado <32.3){
            lbResultado.setText("Acima do peso ideal");
        }if(resultado > 32.3){
            lbResultado.setText("Obeso");
        }
            case 2 :
                if(resultado < 20.7){
            lbResultado.setText("Abaixo do peso");
        }if(resultado > 20.7 && resultado < 26.4){
            lbResultado.setText("Peso normal");
        }if(resultado > 26.4 && resultado <27.8){
            lbResultado.setText("Marginalmente acima do peso");
        }if(resultado > 27.8 && resultado <31.1){
            lbResultado.setText("Acima do peso ideal");
        }if(resultado > 31.1){
            lbResultado.setText("Obeso");
            }
        }
         
    }//GEN-LAST:event_btCalculaPesoActionPerformed

    private void labelAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAlturaActionPerformed

    private void labelSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculaPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField labelAltura;
    private javax.swing.JTextField labelPeso;
    private javax.swing.JTextField labelSexo;
    private javax.swing.JLabel lbResultado;
    // End of variables declaration//GEN-END:variables
}
